title: Personalised Skincare Recommendation System
# logo: /assets/img/
description: 1st Year Data Science Project as part of my BSc Data Science with BPP University
# show_downloads: true
theme: jekyll-theme-cayman
